sudo: true

language: node_js

node_js:
  - "node"

after_success: npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: dev
  target_branch: master
  local_dir: build
